// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk9SkH7jdxcZbu4Ih26CF3_2XAHuKbU-Y',
    appId: '1:551531978702:web:3f1d1787539a113758159f',
    messagingSenderId: '551531978702',
    projectId: 'loginpage-8e6dd',
    authDomain: 'loginpage-8e6dd.firebaseapp.com',
    storageBucket: 'loginpage-8e6dd.appspot.com',
    measurementId: 'G-NWLKBT33BK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBmh0TiZSEKUBTQPE_W8rOA7A9GeUbB0Y',
    appId: '1:551531978702:android:b8046d4981d1f8fa58159f',
    messagingSenderId: '551531978702',
    projectId: 'loginpage-8e6dd',
    storageBucket: 'loginpage-8e6dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwgxwp3cXOHFHW3yEoJFk48QaIEQUHLFc',
    appId: '1:551531978702:ios:e4bb531cf67eb04c58159f',
    messagingSenderId: '551531978702',
    projectId: 'loginpage-8e6dd',
    storageBucket: 'loginpage-8e6dd.appspot.com',
    iosBundleId: 'com.example.eCom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwgxwp3cXOHFHW3yEoJFk48QaIEQUHLFc',
    appId: '1:551531978702:ios:e4bb531cf67eb04c58159f',
    messagingSenderId: '551531978702',
    projectId: 'loginpage-8e6dd',
    storageBucket: 'loginpage-8e6dd.appspot.com',
    iosBundleId: 'com.example.eCom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk9SkH7jdxcZbu4Ih26CF3_2XAHuKbU-Y',
    appId: '1:551531978702:web:03ed1c998762450458159f',
    messagingSenderId: '551531978702',
    projectId: 'loginpage-8e6dd',
    authDomain: 'loginpage-8e6dd.firebaseapp.com',
    storageBucket: 'loginpage-8e6dd.appspot.com',
    measurementId: 'G-4CTKPG1NLK',
  );
}
